postgresql:
  username: postgres
  password: Loken
  host: postgres
  port: 5432
  dbname: devdb
  poolsize: 100

redis:
  host: redis
  port: 6379
  password: ""
  dbnumber: 0

port: 8080
host: localhost
loglvl : debug

token:
  access_public: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBTkRIZTdNZXdKWURrSE9sM0owekxibHoycm1xOHNyMQpZaWhQQkROL1I1djZOTkRTNEhzZUVTeGNjdGxQQ3ZyUnNBZW5HeWhvTldXaEdxZzgzblhOZ0hVQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
  access_private: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT2dJQkFBSkJBTkRIZTdNZXdKWURrSE9sM0owekxibHoycm1xOHNyMVlpaFBCRE4vUjV2Nk5ORFM0SHNlCkVTeGNjdGxQQ3ZyUnNBZW5HeWhvTldXaEdxZzgzblhOZ0hVQ0F3RUFBUUpBRGMyeW13UWtmWWFjelZpZy9tKzgKelM4Z3ZmZlVkNkREcmFDVHlZZlh4ek1rQ210Q3Z3WU44T2FpTitwb0VvbWtHTFVKakVwZXRwYU9tZ1BHSkNNbgpYUUloQVAwdXJWVUpDeUlFeW1CbjkwWi8zdWVmRnRGZElVNlJWRFd1Vk5MVlRiRm5BaUVBMHhwTThUbm1OaXhTCmZrc0ZhSnlrU1FJYnc3Z0ZjRzY1TGZlVWZya1BTY01DSUVaUVpWRWRmdHNHeTVHMHJnY0ZVa212ZEMzWEdIM3kKZkptZi9lekQwcHozQWlCMUxaSXNESEdHL0k5RjN5cS9hTU9nYXZVeWJNRklLWTNNd0RMRExNSVp0UUloQU1MOAplZWErZ1RHc2VpTTJZL0hwYko3dnhPMGprdFZveHRBMGxmaHR4cTR6Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
  refresh_public: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBTHl3OGIrYWZxLyt0bVMrckNnbTVXZ1RTVURRU0VNSAo1S2FldlR3OVhrVytOVGwzR05PMUtHakVBaEptVHhsRVk3MytaT2t4czNaMGtjTWJGSDJHNWxzQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVk=
  refresh_private: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT1FJQkFBSkJBTHl3OGIrYWZxLyt0bVMrckNnbTVXZ1RTVURRU0VNSDVLYWV2VHc5WGtXK05UbDNHTk8xCktHakVBaEptVHhsRVk3MytaT2t4czNaMGtjTWJGSDJHNWxzQ0F3RUFBUUpBZFJrZVBia0VDL1ozZkpmendNczYKck5iaksreldHM3NuZzl1Wk5td2pPQVhiM0dOY1RwZVg0Yi9lYWo1WUoxY1pRbW1BRXNQLzNrZXNXL3pNUisvTQpHUUloQU8zNlFyRHowY1NTNHhqa1hZcW1wb2g2MS9IQzdxdSt6KzNCTGNDMEdOZVhBaUVBeXZzbmlSMmJCc1U3ClBhemYyNFRMRlpoL1pLQm5pS05DSjM1ZDJERUNuOTBDSURvL2ZCMWx3RjFWK3FINEczRTVjeCtLdWRwaDlSc3kKZkNCY25UOUNsYVlIQWlBa2xsTFJCMUliVFUvWlZTRGdxN1lEaFlKbysvVE5qMGZzWUgyLzYwMml6UUlnV1k4MApQdVRtb3R4N2Y0RW95Yk1UQjdyWGJ6T1dHanJDeUYrMStFbSt1Tkk9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
  access_ttl: 15 
  refresh_ttl: 60
